### ISSUE TITLE
How does driver connections work at scale

### ISSUE THREAD

**Issue by ghost** [neo4j-examples/movies-golang-bolt#35]
When we create driver we can provider some configuration values like what should be the connection pool size, so if applications scales will it open multiple driver?

**Comment by fbiville** [comment]
Hello, this kind of question is better suited for https://community.neo4j.com/. 

Each driver instance encapsulates its own connection pool.

What generally needs to scale is the max number of connections (default: 100) in the connection pool, not the number of drivers. You only need multiple drivers if:

1. you target different Neo4j servers/clusters in the same application
2. you need to run queries with different Neo4j users in the same application

Note that point 2 is not true with [Neo4j 4.4](https://neo4j.com/blog/neo4j-4-4-the-fastest-path-to-graph-database-productivity-generally-available/) Enterprise Edition, since you can impersonate users at the session level now, so you don't need to instantiate 1 driver per user anymore.

Does that help?

**Comment by fbiville** [comment]
Closing but feel free to reopen or ask in https://community.neo4j.com/
